# Generated by Django 5.2.10 on 2026-03-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_notification_sender'),
        ('consumer', '0008_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
    ]
