# Generated by Django 5.2.10 on 2026-02-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('pulses', 'Pulses'), ('spices', 'Spices'), ('others', 'Others')], default='vegetables', max_length=20),
        ),
    ]
