# Generated by Django 5.2.10 on 2026-03-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plant_probability', models.FloatField(blank=True, null=True)),
                ('plant_common_names', models.CharField(blank=True, max_length=500, null=True)),
                ('plant_description', models.TextField(blank=True, null=True)),
                ('plant_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_healthy', models.BooleanField(null=True)),
                ('health_probability', models.FloatField(blank=True, null=True)),
                ('disease_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disease_probability', models.FloatField(blank=True, null=True)),
                ('disease_description', models.TextField(blank=True, null=True)),
                ('disease_treatment', models.JSONField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
