# Generated by Django 5.2.10 on 2026-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_governmentscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
