# Generated by Django 5.2.10 on 2026-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_governmentscheme_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Details about who is eligible for this scheme', null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='related_documents',
            field=models.TextField(blank=True, help_text='List of documents required to apply', null=True),
        ),
    ]
