# Generated by Django 5.2.10 on 2026-03-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_upi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='upi_id',
        ),
    ]
